### ISSUE TITLE
how do i use it

### ISSUE THREAD

**Issue by ainc0inei0nipn** [spongecattle/typecheat#3]
how does this work

**Comment by LoganDark** [comment]
It's a tampermonkey script.

**Comment by ainc0inei0nipn** [comment]
i have tampermonkey but idk how to use it, i installed the script but nothing happens in tr

**Comment by ainc0inei0nipn** [comment]
pls help i said to my friend that i can type 140wpm but i lied i need to know how to use this

**Comment by ainc0inei0nipn** [comment]
could it be because when checking the syntax is says: function declarations should not be placed in blocks. use a function expression or move the statement to the top of the outer function

**Comment by ainc0inei0nipn** [comment]
do you guys have twitter or discord? would it be easier to contact you like that?!!

**Comment by LoganDark** [comment]
ʟᴏɢᴀɴᴅᴀʀᴋ™#7425 discord

**Comment by Colean128** [comment]
hello @ainc0inei0nipn I need you to copy typecheat.js again into the user script with the whole thing SELECT ALL'D it works fine for me
